# Form implementation generated from reading ui file 'UI/main_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 731)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.widget_icons = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_icons.setMinimumSize(QtCore.QSize(70, 0))
        self.widget_icons.setMaximumSize(QtCore.QSize(70, 16777215))
        self.widget_icons.setStyleSheet("QWidget {\n"
"    background-color: #71C562;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    height: 30px;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"}")
        self.widget_icons.setObjectName("widget_icons")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_icons)
        self.verticalLayout_6.setContentsMargins(-1, 30, -1, 50)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.logo_1 = QtWidgets.QLabel(parent=self.widget_icons)
        self.logo_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logo_1.setStyleSheet("")
        self.logo_1.setText("")
        self.logo_1.setPixmap(QtGui.QPixmap("UI\\../assets/images/μsic_sync-removebg.png"))
        self.logo_1.setScaledContents(True)
        self.logo_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo_1.setObjectName("logo_1")
        self.horizontalLayout.addWidget(self.logo_1)
        spacerItem1 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home1 = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home1.sizePolicy().hasHeightForWidth())
        self.home1.setSizePolicy(sizePolicy)
        self.home1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home1.setStyleSheet("QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.home1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/musical-note.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home1.setIcon(icon)
        self.home1.setIconSize(QtCore.QSize(30, 30))
        self.home1.setCheckable(True)
        self.home1.setAutoExclusive(True)
        self.home1.setObjectName("home1")
        self.verticalLayout.addWidget(self.home1)
        self.local1 = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local1.sizePolicy().hasHeightForWidth())
        self.local1.setSizePolicy(sizePolicy)
        self.local1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.local1.setStyleSheet("QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.local1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/local-play-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.local1.setIcon(icon1)
        self.local1.setIconSize(QtCore.QSize(30, 30))
        self.local1.setCheckable(True)
        self.local1.setAutoExclusive(True)
        self.local1.setObjectName("local1")
        self.verticalLayout.addWidget(self.local1)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(36, 426, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.about1 = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about1.sizePolicy().hasHeightForWidth())
        self.about1.setSizePolicy(sizePolicy)
        self.about1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.about1.setStyleSheet("QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.about1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about1.setIcon(icon2)
        self.about1.setIconSize(QtCore.QSize(30, 30))
        self.about1.setCheckable(True)
        self.about1.setAutoExclusive(True)
        self.about1.setObjectName("about1")
        self.verticalLayout_3.addWidget(self.about1)
        self.user1 = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user1.sizePolicy().hasHeightForWidth())
        self.user1.setSizePolicy(sizePolicy)
        self.user1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.user1.setStyleSheet("QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.user1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user1.setIcon(icon3)
        self.user1.setIconSize(QtCore.QSize(30, 30))
        self.user1.setCheckable(True)
        self.user1.setAutoExclusive(True)
        self.user1.setObjectName("user1")
        self.verticalLayout_3.addWidget(self.user1)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.main_layout.addWidget(self.widget_icons)
        self.widget_icontexts = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_icontexts.setMinimumSize(QtCore.QSize(161, 0))
        self.widget_icontexts.setMaximumSize(QtCore.QSize(161, 16777215))
        self.widget_icontexts.setStyleSheet("QWidget {\n"
"    background-color: #71C562;\n"
"    color: white;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    height: 30px;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"}")
        self.widget_icontexts.setObjectName("widget_icontexts")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_icontexts)
        self.verticalLayout_5.setContentsMargins(-1, 30, -1, 50)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logo_2 = QtWidgets.QLabel(parent=self.widget_icontexts)
        self.logo_2.setMaximumSize(QtCore.QSize(100, 50))
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("UI\\../assets/images/μsic_sync_with_name-removebg.png"))
        self.logo_2.setScaledContents(True)
        self.logo_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo_2.setObjectName("logo_2")
        self.verticalLayout_5.addWidget(self.logo_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home2 = QtWidgets.QPushButton(parent=self.widget_icontexts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home2.sizePolicy().hasHeightForWidth())
        self.home2.setSizePolicy(sizePolicy)
        self.home2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home2.setStyleSheet("QPushButton {\n"
"    height: 30px;\n"
"    border: none;\n"
"    font-size: 18px;\n"
"    padding-left: -30px\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.home2.setIcon(icon)
        self.home2.setIconSize(QtCore.QSize(30, 30))
        self.home2.setCheckable(True)
        self.home2.setAutoExclusive(True)
        self.home2.setObjectName("home2")
        self.verticalLayout_2.addWidget(self.home2)
        self.local2 = QtWidgets.QPushButton(parent=self.widget_icontexts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local2.sizePolicy().hasHeightForWidth())
        self.local2.setSizePolicy(sizePolicy)
        self.local2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.local2.setStyleSheet("QPushButton {\n"
"    height: 30px;\n"
"    border: none;\n"
"    font-size: 18px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.local2.setIcon(icon1)
        self.local2.setIconSize(QtCore.QSize(30, 30))
        self.local2.setCheckable(True)
        self.local2.setAutoExclusive(True)
        self.local2.setObjectName("local2")
        self.verticalLayout_2.addWidget(self.local2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(38, 316, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.about2 = QtWidgets.QPushButton(parent=self.widget_icontexts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about2.sizePolicy().hasHeightForWidth())
        self.about2.setSizePolicy(sizePolicy)
        self.about2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.about2.setStyleSheet("QPushButton {\n"
"    height: 30px;\n"
"    border: none;\n"
"    font-size: 18px;\n"
"    padding-left: -30px\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.about2.setIcon(icon2)
        self.about2.setIconSize(QtCore.QSize(30, 30))
        self.about2.setCheckable(True)
        self.about2.setAutoExclusive(True)
        self.about2.setObjectName("about2")
        self.verticalLayout_4.addWidget(self.about2)
        self.user2 = QtWidgets.QPushButton(parent=self.widget_icontexts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user2.sizePolicy().hasHeightForWidth())
        self.user2.setSizePolicy(sizePolicy)
        self.user2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.user2.setStyleSheet("QPushButton {\n"
"    height: 30px;\n"
"    border: none;\n"
"    font-size: 18px;\n"
"    padding-left: -40px\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: white;\n"
"    color: #71C562;\n"
"    border-radius: 10px;\n"
"}")
        self.user2.setIcon(icon3)
        self.user2.setIconSize(QtCore.QSize(30, 30))
        self.user2.setCheckable(True)
        self.user2.setAutoExclusive(True)
        self.user2.setObjectName("user2")
        self.verticalLayout_4.addWidget(self.user2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.main_layout.addWidget(self.widget_icontexts)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.header = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(900, 41))
        self.header.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.header.setObjectName("header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.burger_icon = QtWidgets.QPushButton(parent=self.header)
        self.burger_icon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.burger_icon.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid black;\n"
"}")
        self.burger_icon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/burger-bar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.burger_icon.setIcon(icon4)
        self.burger_icon.setIconSize(QtCore.QSize(30, 30))
        self.burger_icon.setCheckable(True)
        self.burger_icon.setObjectName("burger_icon")
        self.horizontalLayout_2.addWidget(self.burger_icon)
        self.page_label = QtWidgets.QLabel(parent=self.header)
        self.page_label.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";\n"
"color: black;")
        self.page_label.setObjectName("page_label")
        self.horizontalLayout_2.addWidget(self.page_label)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(655, 36, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.header)
        self.main_screen = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_screen.sizePolicy().hasHeightForWidth())
        self.main_screen.setSizePolicy(sizePolicy)
        self.main_screen.setStyleSheet("")
        self.main_screen.setObjectName("main_screen")
        self.main_screen_layout = QtWidgets.QVBoxLayout(self.main_screen)
        self.main_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.main_screen_layout.setSpacing(0)
        self.main_screen_layout.setObjectName("main_screen_layout")
        self.home_stack = QtWidgets.QStackedWidget(parent=self.main_screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_stack.sizePolicy().hasHeightForWidth())
        self.home_stack.setSizePolicy(sizePolicy)
        self.home_stack.setObjectName("home_stack")
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.label_4 = QtWidgets.QLabel(parent=self.homepage)
        self.label_4.setGeometry(QtCore.QRect(30, 0, 711, 51))
        self.label_4.setStyleSheet("font: 22pt \"Arial Rounded MT Bold\";\n"
"color: black")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.homepage)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 711, 51))
        self.label_5.setStyleSheet("font: 22pt \"Arial Rounded MT Bold\";\n"
"color: black")
        self.label_5.setObjectName("label_5")
        self.home_stack.addWidget(self.homepage)
        self.local_page = QtWidgets.QWidget()
        self.local_page.setObjectName("local_page")
        self.label_6 = QtWidgets.QLabel(parent=self.local_page)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 741, 61))
        self.label_6.setStyleSheet("font: 22pt \"Arial Rounded MT Bold\";\n"
"color: black;")
        self.label_6.setObjectName("label_6")
        self.content_layout = QtWidgets.QFrame(parent=self.local_page)
        self.content_layout.setGeometry(QtCore.QRect(30, 70, 861, 531))
        self.content_layout.setStyleSheet("QFrame {\n"
"    background-color: #555;\n"
"    border-radius: 30px\n"
"}")
        self.content_layout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content_layout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content_layout.setObjectName("content_layout")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.content_layout)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 821, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.list_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.list_layout.setContentsMargins(0, 0, 0, 0)
        self.list_layout.setObjectName("list_layout")
        self.home_stack.addWidget(self.local_page)
        self.main_screen_layout.addWidget(self.home_stack)
        self.verticalLayout_7.addWidget(self.main_screen)
        self.main_layout.addLayout(self.verticalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.home_stack.setCurrentIndex(0)
        self.home2.toggled['bool'].connect(self.home1.setChecked) # type: ignore
        self.local2.toggled['bool'].connect(self.local1.setChecked) # type: ignore
        self.about2.toggled['bool'].connect(self.about1.setChecked) # type: ignore
        self.user2.toggled['bool'].connect(self.user1.setChecked) # type: ignore
        self.burger_icon.toggled['bool'].connect(self.widget_icontexts.setHidden) # type: ignore
        self.burger_icon.toggled['bool'].connect(self.widget_icons.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home2.setText(_translate("MainWindow", "  Home"))
        self.local2.setText(_translate("MainWindow", " Local Play"))
        self.about2.setText(_translate("MainWindow", " About"))
        self.user2.setText(_translate("MainWindow", " User"))
        self.page_label.setText(_translate("MainWindow", "HOME"))
        self.label_4.setText(_translate("MainWindow", "Recommended Songs"))
        self.label_5.setText(_translate("MainWindow", "Recommended Artists"))
        self.label_6.setText(_translate("MainWindow", "Songs from your local file"))