# Form implementation generated from reading ui file 'UI/main_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 731)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")

        self.widget_icons = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_icons.setMinimumSize(QtCore.QSize(70, 0))
        self.widget_icons.setMaximumSize(QtCore.QSize(70, 16777215))
        self.widget_icons.setStyleSheet("QWidget {\n"
            " background-color: #71C562;\n"
            " color: white;\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            " border: none;\n"
            " height: 30px;\n"
            " padding-top: 5px;\n"
            " padding-bottom: 5px;\n"
            "}")
        self.widget_icons.setObjectName("widget_icons")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_icons)
        self.verticalLayout_6.setContentsMargins(-1, 30, -1, 50)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.logo_1 = QtWidgets.QLabel(parent=self.widget_icons)
        self.logo_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logo_1.setText("")
        self.logo_1.setPixmap(QtGui.QPixmap("UI\\../assets/images/μsic_sync-removebg.png"))
        self.logo_1.setScaledContents(True)
        self.logo_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo_1.setObjectName("logo_1")
        self.horizontalLayout.addWidget(self.logo_1)
        spacerItem1 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")

        self.music_main = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_main.sizePolicy().hasHeightForWidth())
        self.music_main.setSizePolicy(sizePolicy)
        self.music_main.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.music_main.setStyleSheet("QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.music_main.setText("")
        icon_music = QtGui.QIcon()
        icon_music.addPixmap(QtGui.QPixmap(":/icons/music.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.music_main.setIcon(icon_music)
        self.music_main.setIconSize(QtCore.QSize(30, 30))
        self.music_main.setCheckable(True)
        self.music_main.setAutoExclusive(True)
        self.music_main.setObjectName("music_main")
        self.verticalLayout.addWidget(self.music_main)

        self.movies_main = QtWidgets.QPushButton(parent=self.widget_icons)
        self.movies_main.setSizePolicy(sizePolicy)
        self.movies_main.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.movies_main.setStyleSheet("QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #E50914;\n"
            " border-radius: 10px;\n"
            "}")
        self.movies_main.setText("")
        icon_movies = QtGui.QIcon()
        icon_movies.addPixmap(QtGui.QPixmap(":/icons/movies.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.movies_main.setIcon(icon_movies)
        self.movies_main.setIconSize(QtCore.QSize(30, 30))
        self.movies_main.setCheckable(True)
        self.movies_main.setAutoExclusive(True)
        self.movies_main.setObjectName("movies_main")
        self.verticalLayout.addWidget(self.movies_main)

        self.games_main = QtWidgets.QPushButton(parent=self.widget_icons)
        self.games_main.setSizePolicy(sizePolicy)
        self.games_main.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.games_main.setStyleSheet("QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #092f94;\n"
            " border-radius: 10px;\n"
            "}")
        self.games_main.setText("")
        icon_games = QtGui.QIcon()
        icon_games.addPixmap(QtGui.QPixmap(":/icons/games.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.games_main.setIcon(icon_games)
        self.games_main.setIconSize(QtCore.QSize(30, 30))
        self.games_main.setCheckable(True)
        self.games_main.setAutoExclusive(True)
        self.games_main.setObjectName("games_main")
        self.verticalLayout.addWidget(self.games_main)

        self.verticalLayout_6.addLayout(self.verticalLayout)

        spacerItem2 = QtWidgets.QSpacerItem(36, 426, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.about1 = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about1.sizePolicy().hasHeightForWidth())
        self.about1.setSizePolicy(sizePolicy)
        self.about1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.about1.setStyleSheet("QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.about1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about1.setIcon(icon2)
        self.about1.setIconSize(QtCore.QSize(30, 30))
        self.about1.setCheckable(True)
        self.about1.setAutoExclusive(True)
        self.about1.setObjectName("about1")
        self.verticalLayout_3.addWidget(self.about1)

        self.user1 = QtWidgets.QPushButton(parent=self.widget_icons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user1.sizePolicy().hasHeightForWidth())
        self.user1.setSizePolicy(sizePolicy)
        self.user1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.user1.setStyleSheet("QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.user1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user1.setIcon(icon3)
        self.user1.setIconSize(QtCore.QSize(30, 30))
        self.user1.setCheckable(True)
        self.user1.setAutoExclusive(True)
        self.user1.setObjectName("user1")
        self.verticalLayout_3.addWidget(self.user1)

        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.main_layout.addWidget(self.widget_icons)

        self.widget_icontexts = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_icontexts.setMinimumSize(QtCore.QSize(161, 0))
        self.widget_icontexts.setMaximumSize(QtCore.QSize(161, 16777215))
        self.widget_icontexts.setStyleSheet("QWidget {\n"
            " background-color: #71C562;\n"
            " color: white;\n"
            "}\n"
            "QPushButton {\n"
            " border: none;\n"
            " Con height: 30px;\n"
            " padding-top: 5px;\n"
            " padding-bottom: 5px;\n"
            "}")
        self.widget_icontexts.setObjectName("widget_icontexts")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_icontexts)
        self.verticalLayout_5.setContentsMargins(-1, 30, -1, 50)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.logo_2 = QtWidgets.QLabel(parent=self.widget_icontexts)
        self.logo_2.setMaximumSize(QtCore.QSize(100, 50))
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("UI\\../assets/images/μsic_sync_with_name-removebg.png"))
        self.logo_2.setScaledContents(True)
        self.logo_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.logo_2.setObjectName("logo_2")
        self.verticalLayout_5.addWidget(self.logo_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.music_main_text = QtWidgets.QPushButton(parent=self.widget_icontexts)
        self.music_main_text.setSizePolicy(sizePolicy)
        self.music_main_text.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.music_main_text.setStyleSheet("QPushButton {\n"
            " height: 30px;\n"
            " border: none;\n"
            " font-size: 18px;\n"
            "}\n"
            "QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.music_main_text.setIcon(icon_music)
        self.music_main_text.setIconSize(QtCore.QSize(30, 30))
        self.music_main_text.setCheckable(True)
        self.music_main_text.setAutoExclusive(True)
        self.music_main_text.setObjectName("music_main_text")
        self.verticalLayout_2.addWidget(self.music_main_text)

        self.movies_main_text = QtWidgets.QPushButton(parent=self.widget_icontexts)
        self.movies_main_text.setSizePolicy(sizePolicy)
        self.movies_main_text.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.movies_main_text.setStyleSheet("QPushButton {\n"
            " height: 30px;\n"
            " border: none;\n"
            " font-size: 18px;\n"
            "}\n"
            "QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.movies_main_text.setIcon(icon_movies)
        self.movies_main_text.setIconSize(QtCore.QSize(30, 30))
        self.movies_main_text.setCheckable(True)
        self.movies_main_text.setAutoExclusive(True)
        self.movies_main_text.setObjectName("movies_main_text")
        self.verticalLayout_2.addWidget(self.movies_main_text)

        self.games_main_text = QtWidgets.QPushButton(parent=self.widget_icontexts)
        self.games_main_text.setSizePolicy(sizePolicy)
        self.games_main_text.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.games_main_text.setStyleSheet("QPushButton {\n"
            " height: 30px;\n"
            " border: none;\n"
            " font-size: 18px;\n"
            "}\n"
            "QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.games_main_text.setIcon(icon_games)
        self.games_main_text.setIconSize(QtCore.QSize(30, 30))
        self.games_main_text.setCheckable(True)
        self.games_main_text.setAutoExclusive(True)
        self.games_main_text.setObjectName("games_main_text")
        self.verticalLayout_2.addWidget(self.games_main_text)

        self.verticalLayout_5.addLayout(self.verticalLayout_2)

        spacerItem3 = QtWidgets.QSpacerItem(38, 316, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.about2 = QtWidgets.QPushButton(parent=self.widget_icontexts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about2.sizePolicy().hasHeightForWidth())
        self.about2.setSizePolicy(sizePolicy)
        self.about2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.about2.setStyleSheet("QPushButton {\n"
            " height: 30px;\n"
            " border: none;\n"
            " font-size: 18px;\n"
            " padding-left: -30px\n"
            "}\n"
            "QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.about2.setIcon(icon2)
        self.about2.setIconSize(QtCore.QSize(30, 30))
        self.about2.setCheckable(True)
        self.about2.setAutoExclusive(True)
        self.about2.setObjectName("about2")
        self.verticalLayout_4.addWidget(self.about2)

        self.user2 = QtWidgets.QPushButton(parent=self.widget_icontexts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user2.sizePolicy().hasHeightForWidth())
        self.user2.setSizePolicy(sizePolicy)
        self.user2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.user2.setStyleSheet("QPushButton {\n"
            " height: 30px;\n"
            " border: none;\n"
            " font-size: 18px;\n"
            " padding-left: -40px\n"
            "}\n"
            "QPushButton:checked {\n"
            " background-color: white;\n"
            " color: #71C562;\n"
            " border-radius: 10px;\n"
            "}")
        self.user2.setIcon(icon3)
        self.user2.setIconSize(QtCore.QSize(30, 30))
        self.user2.setCheckable(True)
        self.user2.setAutoExclusive(True)
        self.user2.setObjectName("user2")
        self.verticalLayout_4.addWidget(self.user2)

        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.main_layout.addWidget(self.widget_icontexts)

        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.header = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(900, 41))
        self.header.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.header.setObjectName("header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.burger_icon = QtWidgets.QPushButton(parent=self.header)
        self.burger_icon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.burger_icon.setStyleSheet("QPushButton {\n"
            " background: none;\n"
            " border: none;\n"
            " border-radius: 5px;\n"
            "}\n"
            "QPushButton:hover {\n"
            " border: 2px solid black;\n"
            "}")
        self.burger_icon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/burger-bar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.burger_icon.setIcon(icon4)
        self.burger_icon.setIconSize(QtCore.QSize(30, 30))
        self.burger_icon.setCheckable(True)
        self.burger_icon.setObjectName("burger_icon")
        self.horizontalLayout_2.addWidget(self.burger_icon)
        self.page_label = QtWidgets.QLabel(parent=self.header)
        self.page_label.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";\n"
            "color: black;")
        self.page_label.setObjectName("page_label")
        self.horizontalLayout_2.addWidget(self.page_label)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(655, 36, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.header)

        self.top_tabs = QtWidgets.QWidget(parent=self.centralwidget)
        self.top_tabs.setMinimumSize(QtCore.QSize(0, 50))
        self.top_tabs.setStyleSheet("background-color: rgb(245, 245, 245); border-bottom: 1px solid #ddd;")
        self.top_tabs.setObjectName("top_tabs")
        self.tabs_layout = QtWidgets.QHBoxLayout(self.top_tabs)
        self.tabs_layout.setContentsMargins(20, 0, 0, 0)
        self.tabs_layout.setSpacing(30)
        self.tabs_layout.setObjectName("tabs_layout")

        # === MUSIC TABS ===
        self.tab_home = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_home.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_home.setStyleSheet("QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
                                    "QPushButton:checked { color: #71C562; border-bottom: 4px solid #71C562; }")
        self.tab_home.setText("Home")
        self.tab_home.setCheckable(True)
        self.tab_home.setChecked(True)
        self.tab_home.setObjectName("tab_home")
        self.tabs_layout.addWidget(self.tab_home)

        self.tab_genre = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_genre.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_genre.setStyleSheet("QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
                                     "QPushButton:checked { color: #71C562; border-bottom: 4px solid #71C562; }")
        self.tab_genre.setText("Music Genre")
        self.tab_genre.setCheckable(True)
        self.tab_genre.setObjectName("tab_genre")
        self.tabs_layout.addWidget(self.tab_genre)

        self.tab_search = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_search.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_search.setStyleSheet("QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
                                      "QPushButton:checked { color: #71C562; border-bottom: 4px solid #71C562; }")
        self.tab_search.setText("Search Music")
        self.tab_search.setCheckable(True)
        self.tab_search.setObjectName("tab_search")
        self.tabs_layout.addWidget(self.tab_search)

        self.tab_local = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_local.setMinimumSize(QtCore.QSize(140, 40))
        self.tab_local.setStyleSheet("QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
                                     "QPushButton:checked { color: #71C562; border-bottom: 4px solid #71C562; }")
        self.tab_local.setText("Local Play")
        self.tab_local.setCheckable(True)
        self.tab_local.setObjectName("tab_local")
        self.tabs_layout.addWidget(self.tab_local)

        # === MOVIE TABS (initially hidden) ===
        self.tab_movie_home = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_movie_home.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_movie_home.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #E50914; border-bottom: 4px solid #E50914; }")
        self.tab_movie_home.setText("Home")
        self.tab_movie_home.setCheckable(True)
        self.tab_movie_home.setVisible(False)
        self.tab_movie_home.setObjectName("tab_movie_home")
        self.tabs_layout.addWidget(self.tab_movie_home)

        self.tab_tvshows = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_tvshows.setMinimumSize(QtCore.QSize(140, 40))
        self.tab_tvshows.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #E50914; border-bottom: 4px solid #E50914; }")
        self.tab_tvshows.setText("TV Shows")
        self.tab_tvshows.setCheckable(True)
        self.tab_tvshows.setVisible(False)
        self.tab_tvshows.setObjectName("tab_tvshows")
        self.tabs_layout.addWidget(self.tab_tvshows)

        self.tab_movies = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_movies.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_movies.setStyleSheet("QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
                                      "QPushButton:checked { color: #E50914; border-bottom: 4px solid #E50914; }")
        self.tab_movies.setText("Movies")
        self.tab_movies.setCheckable(True)
        self.tab_movies.setVisible(False)
        self.tab_movies.setObjectName("tab_movies")
        self.tabs_layout.addWidget(self.tab_movies)

        self.tab_movie_genre = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_movie_genre.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_movie_genre.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #E50914; border-bottom: 4px solid #E50914; }")
        self.tab_movie_genre.setText("Genre")
        self.tab_movie_genre.setCheckable(True)
        self.tab_movie_genre.setVisible(False)
        self.tab_movie_genre.setObjectName("tab_movie_genre")
        self.tabs_layout.addWidget(self.tab_movie_genre)

        self.tab_movie_search = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_movie_search.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_movie_search.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #E50914; border-bottom: 4px solid #E50914; }")
        self.tab_movie_search.setText("Search")
        self.tab_movie_search.setCheckable(True)
        self.tab_movie_search.setVisible(False)
        self.tab_movie_search.setObjectName("tab_movie_search")
        self.tabs_layout.addWidget(self.tab_movie_search)

        self.movie_tab_group = QtWidgets.QButtonGroup()
        self.movie_tab_group.setExclusive(True)
        self.movie_tab_group.addButton(self.tab_movie_home)
        self.movie_tab_group.addButton(self.tab_tvshows)
        self.movie_tab_group.addButton(self.tab_movies)
        self.movie_tab_group.addButton(self.tab_movie_genre)
        self.movie_tab_group.addButton(self.tab_movie_search)

        # GAME TABS
        self.tab_game_home = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_game_home.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_game_home.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #092f94; border-bottom: 4px solid #092f94; }")
        self.tab_game_home.setText("Home")
        self.tab_game_home.setCheckable(True)
        self.tab_game_home.setChecked(True)
        self.tab_game_home.setVisible(False)
        self.tab_game_home.setObjectName("tab_game_home")
        self.tabs_layout.addWidget(self.tab_game_home)

        self.tab_game_genre = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_game_genre.setMinimumSize(QtCore.QSize(140, 40))
        self.tab_game_genre.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #092f94; border-bottom: 4px solid #092f94; }")
        self.tab_game_genre.setText("Game Genres")
        self.tab_game_genre.setCheckable(True)
        self.tab_game_genre.setVisible(False)
        self.tab_game_genre.setObjectName("tab_game_genre")
        self.tabs_layout.addWidget(self.tab_game_genre)

        self.tab_game_search = QtWidgets.QPushButton(parent=self.top_tabs)
        self.tab_game_search.setMinimumSize(QtCore.QSize(120, 40))
        self.tab_game_search.setStyleSheet(
            "QPushButton { font-size: 14pt; font-weight: bold; border: none; color: #333; }\n"
            "QPushButton:checked { color: #092f94; border-bottom: 4px solid #092f94; }")
        self.tab_game_search.setText("Search Games")
        self.tab_game_search.setCheckable(True)
        self.tab_game_search.setVisible(False)
        self.tab_game_search.setObjectName("tab_game_search")
        self.tabs_layout.addWidget(self.tab_game_search)

        self.game_tab_group = QtWidgets.QButtonGroup()
        self.game_tab_group.setExclusive(True)
        self.game_tab_group.addButton(self.tab_game_home)
        self.game_tab_group.addButton(self.tab_game_genre)
        self.game_tab_group.addButton(self.tab_game_search)

        spacer_tabs = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.tabs_layout.addItem(spacer_tabs)
        self.verticalLayout_7.addWidget(self.top_tabs)

        self.main_screen = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_screen.sizePolicy().hasHeightForWidth())
        self.main_screen.setSizePolicy(sizePolicy)
        self.main_screen.setStyleSheet("")
        self.main_screen.setObjectName("main_screen")
        self.main_screen_layout = QtWidgets.QVBoxLayout(self.main_screen)
        self.main_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.main_screen_layout.setSpacing(0)
        self.main_screen_layout.setObjectName("main_screen_layout")

        self.home_stack = QtWidgets.QStackedWidget(parent=self.main_screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_stack.sizePolicy().hasHeightForWidth())
        self.home_stack.setSizePolicy(sizePolicy)
        self.home_stack.setObjectName("home_stack")

        self.music_stack = QtWidgets.QStackedWidget()
        self.music_stack.setObjectName("music_stack")

        self.movies_stack = QtWidgets.QStackedWidget()
        self.movies_stack.setObjectName("movies_stack")

        self.games_stack = QtWidgets.QStackedWidget()
        self.games_stack.setObjectName("games_stack")

        self.home_stack.addWidget(self.music_stack)
        self.home_stack.addWidget(self.movies_stack)
        self.home_stack.addWidget(self.games_stack)

        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.home_stack.addWidget(self.about_page)

        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.home_stack.addWidget(self.profile_page)

        self.main_screen_layout.addWidget(self.home_stack)
        self.verticalLayout_7.addWidget(self.main_screen)
        self.main_layout.addLayout(self.verticalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.home_stack.setCurrentIndex(0)
        self.music_stack.setCurrentIndex(0)
        self.movies_stack.setCurrentIndex(0)
        self.games_stack.setCurrentIndex(0)
        self.burger_icon.toggled['bool'].connect(self.widget_icontexts.setHidden)
        self.burger_icon.toggled['bool'].connect(self.widget_icons.setVisible)
        self.music_main.toggled['bool'].connect(self.music_main_text.setChecked)
        self.music_main_text.toggled['bool'].connect(self.music_main.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.music_main_text.setText(_translate("MainWindow", " Music"))
        self.movies_main_text.setText(_translate("MainWindow", " Movies"))
        self.games_main_text.setText(_translate("MainWindow", " Games"))
        self.about2.setText(_translate("MainWindow", " About"))
        self.user2.setText(_translate("MainWindow", " User"))
        self.page_label.setText(_translate("MainWindow", "HOME"))