# Form implementation generated from reading ui file 'UI/music_player.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1180, 600)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1180, 600))
        self.widget.setStyleSheet("background-color: #0F0F0F;")
        self.widget.setObjectName("widget")
        self.spinner = QtWidgets.QLabel(parent=self.widget)
        self.spinner.setGeometry(QtCore.QRect(30, 90, 400, 400))
        self.spinner.setMinimumSize(QtCore.QSize(200, 200))
        self.spinner.setStyleSheet("QLabel {\n"
"}")
        self.spinner.setText("")
        self.spinner.setScaledContents(True)
        self.spinner.setObjectName("spinner")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(460, 49, 691, 501))
        self.widget_2.setStyleSheet("background-color: rgb(83, 83, 83);\n"
"border-radius: 50px;")
        self.widget_2.setObjectName("widget_2")
        self.playButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.playButton.setGeometry(QtCore.QRect(310, 280, 100, 100))
        self.playButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.playButton.setStyleSheet("QPushButton {\n"
"    background-color: #1DB954;\n"
"    border: 2px solid white;\n"
"    border-radius: 50px;\n"
"}")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/play.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(60, 60))
        self.playButton.setObjectName("playButton")
        self.prevButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.prevButton.setGeometry(QtCore.QRect(220, 290, 70, 70))
        self.prevButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.prevButton.setStyleSheet("QPushButton {\n"
"    background-color: #1DB954;\n"
"    border: 2px solid white;\n"
"    border-radius: 35px;\n"
"}")
        self.prevButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/prev.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.prevButton.setIcon(icon1)
        self.prevButton.setIconSize(QtCore.QSize(40, 40))
        self.prevButton.setObjectName("prevButton")
        self.nextButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.nextButton.setGeometry(QtCore.QRect(430, 290, 70, 70))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.nextButton.setStyleSheet("QPushButton {\n"
"    background-color: #1DB954;\n"
"    border: 2px solid white;\n"
"    border-radius: 35px;\n"
"}")
        self.nextButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/next.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setIconSize(QtCore.QSize(40, 40))
        self.nextButton.setObjectName("nextButton")
        self.progressTime = QtWidgets.QSlider(parent=self.widget_2)
        self.progressTime.setGeometry(QtCore.QRect(60, 150, 571, 31))
        self.progressTime.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.progressTime.setStyleSheet("QSlider {\n"
"    \n"
"}")
        self.progressTime.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressTime.setObjectName("progressTime")
        self.currentTime = QtWidgets.QLabel(parent=self.widget_2)
        self.currentTime.setGeometry(QtCore.QRect(60, 190, 81, 16))
        self.currentTime.setStyleSheet("QLabel {\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"    color: white;\n"
"}")
        self.currentTime.setObjectName("currentTime")
        self.totalTime = QtWidgets.QLabel(parent=self.widget_2)
        self.totalTime.setGeometry(QtCore.QRect(550, 190, 81, 16))
        self.totalTime.setStyleSheet("QLabel {\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"    color: white;\n"
"}")
        self.totalTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.totalTime.setObjectName("totalTime")
        self.song_title = QtWidgets.QLabel(parent=self.widget_2)
        self.song_title.setGeometry(QtCore.QRect(60, 50, 571, 71))
        self.song_title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    text-transform: uppercase;\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"}")
        self.song_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.song_title.setObjectName("song_title")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.currentTime.setText(_translate("Dialog", "0:00"))
        self.totalTime.setText(_translate("Dialog", "0:00"))
        self.song_title.setText(_translate("Dialog", "Song Title"))
