# Form implementation generated from reading ui file 'UI/signup_screen.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 667)
        self.widget_2 = QtWidgets.QWidget(parent=Dialog)
        self.widget_2.setEnabled(True)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1001, 671))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_2.setGeometry(QtCore.QRect(640, -1, 361, 671))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(37, 172, 48, 255), stop:1 rgba(141, 178, 35, 255));\n"
"border-top-left-radius: 50px;\n"
"border-bottom-left-radius: 50px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(80, 200, 211, 91))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: transparent; ")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.login_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.login_btn.setGeometry(QtCore.QRect(50, 320, 271, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: transparent;\n"
"border: 3px solid white;\n"
"font: 18pt \"Arial\";\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.signup_label = QtWidgets.QLabel(parent=self.widget_2)
        self.signup_label.setGeometry(QtCore.QRect(170, 90, 271, 61))
        self.signup_label.setStyleSheet("font: 75 36pt \"Tw Cen MT\";\n"
"color: black;\n"
"")
        self.signup_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.signup_label.setObjectName("signup_label")
        self.signup_btn = QtWidgets.QPushButton(parent=self.widget_2)
        self.signup_btn.setGeometry(QtCore.QRect(60, 440, 511, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_btn.sizePolicy().hasHeightForWidth())
        self.signup_btn.setSizePolicy(sizePolicy)
        self.signup_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.signup_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(37, 172, 48, 255), stop:1 rgba(141, 178, 35, 255));\n"
"border: 3px solid white;\n"
"font: 18pt \"Arial\";\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"    spread:reflect,\n"
"    x1:0, y1:0, x2:1, y2:0,\n"
"    stop:0 rgba(77, 202, 88, 255),\n"
"    stop:1 rgba(181, 208, 85, 255)\n"
");\n"
"}")
        self.signup_btn.setObjectName("signup_btn")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget_2)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 200, 501, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 3px solid #000000;\n"
"    border-color: rgb(177, 177, 177);\n"
"    border-radius: 20px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"    color: black;\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: black;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 3px solid #000000;\n"
"    border-color: rgb(177, 177, 177);\n"
"    border-radius: 20px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"    color: black;\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: black;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Already have an account?"))
        self.login_btn.setText(_translate("Dialog", "Log In"))
        self.signup_label.setText(_translate("Dialog", "SIGN UP"))
        self.signup_btn.setText(_translate("Dialog", "Sign Up"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Password"))
