# Form implementation generated from reading ui file 'UI/startup_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1020, 680)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #000000;\n"
"}")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(parent=self.widget)
        self.logo.setMinimumSize(QtCore.QSize(70, 70))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("UI\\../assets/images/logo_with_name.png"))
        self.logo.setScaledContents(True)
        self.logo.setMinimumSize(QtCore.QSize(300, 100))
        self.logo.setMaximumSize(QtCore.QSize(350, 130))
        self.logo.setObjectName("logo")

        # Center logo using layout (added)
        self.centerLayout = QtWidgets.QVBoxLayout(self.widget)
        self.centerLayout.setContentsMargins(0, 0, 0, 0)
        self.centerLayout.setSpacing(0)
        self.centerLayout.addStretch()
        self.centerLayout.addWidget(self.logo, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)
        self.centerLayout.addStretch()

        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
