# Form implementation generated from reading ui file 'UI/startup_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1020, 680)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1021, 681))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #71C562;\n"
"}")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(340, 240, 311, 141))
        self.logo.setMinimumSize(QtCore.QSize(70, 70))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("UI\\../assets/images/μsic_sync_with_name-removebg.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
